users:
    resource: "@UserGroupBundle/Resources/config/routing/users.yml"
    prefix:   /users

groups:
    resource: "@UserGroupBundle/Resources/config/routing/groups.yml"
    prefix:   /groups

user_group_homepage:
    path:     /
    defaults: { _controller: "UserGroupBundle:Default:index" }

