InterNations\UserGroupBundle\Entity\Roles:
    type: entity
    table: Roles
    uniqueConstraints:
        RoleName:
            columns:
                - RoleName
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rolename:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: RoleName
    manyToMany:
        userid:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: roleid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
