groups_api_index:
    path:     /
    defaults: { _controller: "UserGroupBundle:GroupsApi:index" }
    methods:  GET

groups_api_show:
    path:     /{id}/show
    defaults: { _controller: "UserGroupBundle:GroupsApi:show" }
    methods:  GET

groups_api_new:
    path:     /new
    defaults: { _controller: "UserGroupBundle:GroupsApi:new" }
    methods:  [GET, POST]

groups_api_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserGroupBundle:GroupsApi:edit" }
    methods:  [GET, POST]

groups_api_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserGroupBundle:GroupsApi:delete" }
    methods:  [GET, DELETE]
