users_index:
    path:     /
    defaults: { _controller: "UserGroupBundle:Users:index" }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "UserGroupBundle:Users:show" }
    methods:  GET

users_new:
    path:     /new
    defaults: { _controller: "UserGroupBundle:Users:new" }
    methods:  [GET, POST]

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserGroupBundle:Users:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserGroupBundle:Users:delete" }
    methods:  [GET, DELETE]

user_group_assign:
    path:     /{id}/assign
    defaults: { _controller: "UserGroupBundle:Users:assign" }
    methods:  [GET, POST]